<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>Web_Framework</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>Turtin Dev</Authors>
        <Company>Turtin Dev</Company>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="file\resources\server.cfg" />
      <EmbeddedResource Include="file\resources\server.cfg" />
    </ItemGroup>

</Project>
